use_frameworks!

target 'PoporAlertBubbleView_Example' do
  pod 'PoporAlertBubbleView', :path => '../'
  
  pod 'PoporUI/UIDeviceScreen'
  
  target 'PoporAlertBubbleView_Tests' do
    inherit! :search_paths

    
  end
end
